---
title: "Assessing precision"
output: learnr::tutorial
runtime: shiny_prerendered
description: "A variety of ways in which precision is reported in model output. Danger signs when precision is a problem."
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```


## Topic 1

### Exercise 

```{r flaws}
question_checkbox("Identify the design flaws of the survey that produced such poor precision (check all that apply)",
  answer("too few replicate transects"),
  answer("ignorance of animal gradient", correct = TRUE),
  answer("truncation too narrow (too few detections)"),
  answer("inadequate survey effort"),
  answer("transects of unequal length")
)
```

```{r double}
question_checkbox("Why is the estimate of abundance exactly half the estimate of density in this analysis? (check all that apply)",
  answer("$\\hat{N} = \\hat{D} \\times A$, where A=1/2", correct = TRUE),
  answer("that is characteristic of the half normal detection function"),
  answer("inadequate survey effort"),
  answer("because of convert_units, square kilometers are twice as large as kilometers")
)
```

```{r boot}
question_checkbox("Why does the use of the bootstrap not resolve the poor precision problem? (check all that apply)",
  answer("bootstrap only improves precision of estimated detection function"),
  answer("bootstrap does not perform well with half normal detection function"),
  answer("resampling transects does not alter variability in encounter rate between transects", correct = TRUE),
  answer("bootstrapping is over-rated, never works well")
)
```


